package dev.jco.carcasses;
import net.minecraft.core.BlockPos;import net.minecraft.nbt.CompoundTag;import net.minecraft.nbt.ListTag;import net.minecraft.nbt.Tag;import net.minecraft.server.level.ServerLevel;import net.minecraft.server.level.ServerPlayer;import net.minecraft.world.*;import net.minecraft.world.item.*;import net.minecraft.world.item.crafting.RecipeType;import net.minecraft.world.level.Level;import net.minecraft.world.level.block.CampfireBlock;import net.minecraft.world.level.block.entity.CampfireBlockEntity;import net.minecraft.world.level.block.state.BlockState;import net.minecraft.world.phys.*;import net.neoforged.neoforge.event.entity.player.PlayerInteractEvent;import net.neoforged.neoforge.network.PacketDistributor;
/** No world scan: loaded campfire block entities consume their own persisted fuel. */
public final class CampfireFuel {
 public static volatile int multiplier=-1;public static final String KEY="jco_fuel";
 public static int activeMultiplier(){return multiplier>=0?multiplier:CookingConfig.multiplier();}
 public static boolean tick(Level level,BlockPos pos,BlockState state,CampfireBlockEntity be){if(activeMultiplier()==0||level.isClientSide||!state.getValue(CampfireBlock.LIT))return true;var n=be.getPersistentData().getCompound(KEY);long left=Math.max(0,n.getLong("remaining")-1);n.putLong("remaining",left);var queue=n.getList("fuelQueue",Tag.TAG_COMPOUND);if(!queue.isEmpty()){var head=queue.getCompound(0);long ticks=head.getLong("ticks")-1;if(ticks<=0)queue.remove(0);else head.putLong("ticks",ticks);}if(left==0)queue.clear();n.put("fuelQueue",queue);be.getPersistentData().put(KEY,n);be.setChanged();if(left>0)return true;level.setBlock(pos,state.setValue(CampfireBlock.LIT,false),3);CampfireBlock.dowse(null,level,pos,state);level.playSound(null,pos,net.minecraft.sounds.SoundEvents.GENERIC_EXTINGUISH_FIRE,net.minecraft.sounds.SoundSource.BLOCKS,.5F,1);return false;}
 public static void interact(PlayerInteractEvent.RightClickBlock event){if(activeMultiplier()==0||event.getHand()!=InteractionHand.MAIN_HAND||event.getEntity().isShiftKeyDown()||!(event.getEntity() instanceof ServerPlayer p)||!(event.getLevel().getBlockEntity(event.getPos()) instanceof CampfireBlockEntity be))return;var stack=p.getMainHandItem();int burn=stack.getBurnTime(RecipeType.SMELTING);if(burn<=0||be.getCookableRecipe(stack).isPresent())return;event.setCanceled(true);event.setCancellationResult(InteractionResult.CONSUME);if(p.isSpectator()||!p.mayBuild()||!p.serverLevel().mayInteract(p,event.getPos())||p.distanceToSqr(Vec3.atCenterOf(event.getPos()))>Math.pow(p.blockInteractionRange()+1,2))return;
  var n=be.getPersistentData().getCompound(KEY);long add=(long)burn*activeMultiplier(),remaining=n.getLong("remaining");if(add>1_000_000_000L-remaining)return;var queue=n.getList("fuelQueue",Tag.TAG_COMPOUND);if(queue.isEmpty()&&remaining>0){var legacy=new CompoundTag();legacy.putLong("ticks",remaining);queue.add(legacy);}var segment=new CompoundTag();segment.putLong("ticks",add);segment.put("item",stack.copyWithCount(1).save(p.level().registryAccess()));queue.add(segment);n.put("fuelQueue",queue);n.putLong("remaining",remaining+add);n.putLong("total",remaining+add);be.getPersistentData().put(KEY,n);be.setChanged();if(!p.isCreative()){var remainder=stack.getCraftingRemainingItem();stack.shrink(1);if(!remainder.isEmpty()&&!p.getInventory().add(remainder))p.drop(remainder,false);}p.swing(event.getHand(),true);p.serverLevel().playSound(null,event.getPos(),net.minecraft.sounds.SoundEvents.WOOD_PLACE,net.minecraft.sounds.SoundSource.BLOCKS,.4F,1.2F);send(p,event.getPos(),be);
 }
 private static void send(ServerPlayer p,BlockPos pos,CampfireBlockEntity be){var n=be.getPersistentData().getCompound(KEY);var queue=n.getList("fuelQueue",Tag.TAG_COMPOUND);var fuel=queue.isEmpty()?ItemStack.EMPTY:ItemStack.parseOptional(p.level().registryAccess(),queue.getCompound(0).getCompound("item"));PacketDistributor.sendToPlayer(p,new FuelPayload(p.level().dimension().location().toString(),pos,n.getLong("remaining"),n.getLong("total"),be.getBlockState().getValue(CampfireBlock.LIT),fuel));}
 public static void playerTick(net.neoforged.neoforge.event.tick.PlayerTickEvent.Post event){if(activeMultiplier()==0||!(event.getEntity() instanceof ServerPlayer p)||p.tickCount%5!=0)return;var hit=p.pick(p.blockInteractionRange(),1,false);if(hit instanceof BlockHitResult b&&hit.getType()==HitResult.Type.BLOCK&&p.level().getBlockEntity(b.getBlockPos()) instanceof CampfireBlockEntity be)send(p,b.getBlockPos(),be);}
}
